version: '3.8'

services:
  dbt:
    build: .
    container_name: dbt
    volumes:
      # - /dbt:/dbt
      # - ./credentials:/credentials
      - ./dbt:/root/.dbt/dbt
      - ./credentials:/credentials
      - ./profiles.yml:/root/.dbt/profiles.yml       
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/keyfile.json
    working_dir: /dbt
    entrypoint: ["tail", "-f", "/dev/null"]

  # superset:
  #   image: apache/superset:latest
  #   container_name: superset
  #   ports:
  #     - "8099:8099"
  #   environment:
  #     SUPERSET_SECRET_KEY: "admin"
  #     FLASK_APP: "superset"
  #   volumes:
  #     - ./superset_home:/app/superset_home
  #     - ./superset_config.py:/app/superset_home/superset_config.py
  #   command: >
  #     superset db upgrade &&
  #     superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin &&
  #     superset init &&
  #     superset run -h 0.0.0.0 -p 8099 --with-threads --reload --debugger

  # superset-init:
  #   image: apache/superset:latest
  #   depends_on:
  #     - superset
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       superset db upgrade &&
  #       superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
  #       superset init

  # airbyte:
  #   image: airbyte/server:build-9376de31b1-20645-master
  #   container_name: airbyte
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped
  #   environment:
  #     - AIRBYTE_ENV="cloud"
  #     - GOOGLE_APPLICATION_CREDENTIALS=/credentials/keyfile.json
  #     - DATABASE_PASSWORD=your_database_password_here
  #   volumes:
  #     - airbyte_data:/data
  #     - ./credentials:/credentials


volumes:
  dbt:
  # superset_home:
  # airbyte_data:
